<?php
require_once 'vendor/autoload.php';

// testing the boot config stuff
$data = json_encode( 
    array(
        "foo" => 'bar',
        "bar" => "baz"
    ) 
);

$params = array(
    'data' => $data,
    'type' => 'dev'
);

echo BIM_App_Config::saveBootConf($params)."\n";

print_r( BIM_App_Config::getBootConf($params) )."\n";

/*
$tags = (object) array(
    'type' => 'ad',
    'quotes' => adQuotes()
);
*/
// BIM_Config::saveQuotes($tags);

//print_r( BIM_Config::adQuotes() );
//print_r( BIM_Config::authenticQuotes() );

function adQuotes(){
    return join(',',array(
         'lol love this (: want to be a tester? bit.ly/volleyapp',
         'swaaaaaggggggggg!!!!! <3<3 are you testing volley? bit.ly/volleyapp',
         'cute pics <3 wanna help me get free itunes cards? bit.ly/volleyapp',
         'LOL!!!!!!!!!! bit.ly/volleyapp',
         'yolo bitch bit.ly/volleyapp',
         'do you have kik? bit.ly/volleyapp',
         'wanna kik? bit.ly/volleyapp',
         'want to volley? want to help me test? bit.ly/volleyapp',
         'SOOOOOOOOOOOOO cute (: bit.ly/volleyapp',
         'i <3 this bit.ly/volleyapp',
         'test with me? bit.ly/volleyapp',
         'i got a free itunes card, lol bit.ly/volleyapp',
         'lol, i gots a free itunes card bit.ly/volleyapp',
         'do you have an iphone bit.ly/volleyapp',
         'do you have an iPhone, wanna help? bit.ly/volleyapp',
         'freee 50 dolla gift cards for itunes bit.ly/volleyapp',
         'iphone? bit.ly/volleyapp',
         'hmu bit.ly/volleyapp',
         'do you have an iphone? bit.ly/volleyapp',
         'want free itunes cards? bit.ly/volleyapp',
         'free itunes cards!!!! yayyyyya! bit.ly/volleyapp',
         'you on volley? testers get free swag bit.ly/volleyapp',
         'volley testers get hoookkkkk up bit.ly/volleyapp',
         'cute pic want free itunes card? bit.ly/volleyapp',
         'bit.ly/volleyapp',
         'do you have kik ? bit.ly/volleyapp',
         'kik? bit.ly/volleyapp',
         'wanna kik me?',
         'do u want a free itunes casrd? bit.ly/volleyapp',
         'i like ur pics bit.ly/volleyapp',
         'ur pics are cool bit.ly/volleyapp',
         'swag on bit.ly/volleyapp',
         'volley testers wanted bit.ly/volleyapp',
         'bit.ly/volleyapp want to test?',
         'get volley yet bit.ly/volleyapp',
         'wanna be an app tester? bit.ly/volleyapp',
         'app tester? bit.ly/volleyapp',
         'wanna test an app with me?',
         'test apps? bit.ly/volleyapp',
         'have an iphone and want to test an app with me?',
         'have an iphone and like apps? bit.ly/volleyapp',
         'hmu if u have an iphone bit.ly/volleyapp',
         'like apps? bit.ly/volleyapp',
         'bit.ly/volleyapp like apps?',
         'want to help test? bit.ly/volleyapp',
         'want to help and own an iphone? bit.ly/volleyapp',
         'want to help and have an iphone? bit.ly/volleyapp',
         'we should volley! bit.ly/volleyapp',
         'want to volley? test this bit.ly/volleyapp',
         'app tester wanted! your cute! bit.ly/volleyapp',
         'want to help me test an app bit.ly/volleyapp',
         'check this out bit.ly/volleyapp',
         'have an iphone and love apps bit.ly/volleyapp',
         'iphone????? test this!! bit.ly/volleyapp',
         'TEST this app!! bit.ly/volleyapp',
         'wanna be an app iphone tester? bit.ly/volleyapp',
         'Test test test test this app bit.ly/volleyapp',
         'you should get up on this bit.ly/volleyapp',
         'check this out boyyyyyyyyyyyy hehe jk bit.ly/volleyapp',
         'like new apps? bit.ly/volleyapp',
         'check this out? bit.ly/volleyapp',
         'wanna test with me bit.ly/volleyapp',
         'bit.ly/volleyapp #app',
         'bit.ly/volleyapp #appinvite',
         'bit.ly/volleyapp #appinvite #appsarecool #tester',
         'DOYOU like apps bit.ly/volleyapp #appinvite',
         'wanna to help test bit.ly/volleyapp #appinvite',
         'tester? bit.ly/volleyapp #appinvite',
         'have an iphone? bit.ly/volleyapp #appinvite',
         'iphone bit.ly/volleyapp #appinvite',
         'iphone? bit.ly/volleyapp #appinvite',
         'want to help? bit.ly/volleyapp #appinvite',
         'help? bit.ly/volleyapp #appinvite',
         'tester wanted! bit.ly/volleyapp #appinvite',
   ) );
}


function getAuthQuotes(){
	   return join(',', array(
			'itsssss summmer!!!!',
			'love this (:',
			'lol, cute!',
			'cute!!!!!!! <3<3',
			'wanna kik?',
			'do you have an iphone?',
			'iphone 5?',
			'wanna instaDM?',
			'love thisssss, love ur pics (:',
			'(: <3',
			'nice',
			'hows ur summer?',
			'out of school?',
			'????',
			'<3',
			'i like',
			'you?',
			'tbh?',
			'rate me?',
			'do you have volley?',
			'!!!!',
			'like?',
			'wanna rate me?',
			'ur cute!',
			'love ur pics',
			'your pics are cute #volley',
			'do you like my pics? #volley',
			'wanna help? #volley',
			'test with me? #volley',
			'u on volley yet? #volley',
			'volley yet? #volley',
			'are you out of school yet? #volley',
			'summer yet? #volley',
			'bored as fuck.#instagram #volley',
			'wanna kik chat? #instagram #volley',
			'wanna chat? #instagram #volley ',
			'do you have volley yet? #instagram #volley',
			'swaggggg #instagram #volley',
			'yolo #instagram #volley',
			'poke #instagram #volley',
			'(: #kik #volley',
			'(: (: $$$$$$ #kik #volley',
			'wannnna chat? #kik #volley',
			'ask.fm? #askfm #volley',
			'wanna ask? #askfm #volley',
			'wanna ask me something? #askfm #volley',
			'you so finnnnnne #volley',
			'what do you think about me? #volley',
			'wanna #volley ?',
			'how low can you go?! #volley',
			'what type of music do you like? #volley',
			'i love this pic  #volley',
			'#volley #askfm #insta',
			'dis is cute #volley #kik #lover',
			'hahah lol!! #volley',
			'wtf? #volley',
			'kik me? #volley',
			'cool pic #volley',
			'#volley me?',
			'wanna volley #volley',
			'hear about #volley yet?',
			'get #volley yet?',
			'did #volley come out yet?',
		 	'#volley #volley #volley',
			'swaggggeriffic ',
			'swag boom !!!',
			'#volley swag mother !!!',
			'sweet #volley',
			'want to trade pics #volley',
			'want free swag?',
			'you like me? #volley',
			'ask me anything? #volley',
			'want to party #volley',
			'#volley me !!!',
		) );
    
}

function getTags(){
        return join(',', array(
            'selfie', 'me', 'self', 'selfpic', 'bff', 'myface', 'rateme', 'duckface',
            "pink","art","hot","instahub","photo","throwbackthursday","statigram","cat",
            "my","family","clouds","amazing","awesome","girls","textgram","jj_forum",
            "all_shots","baby","music","red","repost","black","instalove","igaddict",
            "party","yummy","instago","night","green","white","bestfriend","yum","ignation",
            "followback","harrystyles","eyes","school","foodporn","2012","sweet","style",
            "water","niallhoran","boy","nails","yolo","nice","beauty","i","flower",
            "zaynmalik","best","louistomlinson","liampayne","instacollage","blonde",
            "bestfriends","1d","puppy","flowers","work","instacool","makeup","shoes",
            "insta","adorable","birthday","friend","10likes","likeforlike","gang_family",
            "boyfriend","good","nyc","morning","you","instapic","the","sea","blackandwhite",
            "haha","instaphoto","jusgramm","day","tree","dinner","crazy","20likes",
            "shoutout","throwback","home","gorgeous","true","truth","justinbieber","bieber",
            "mtv","yolo","swag","sister","instaplace","igsg","homework","flashbackfriday",
            "british","warm","skyline","phone","hiphop","styles","tweetgram","jeep","watch","brooklyn",
            "russia","februarychallenge","japanese","instamillion","instanature","son","storm","draw",
            "single","tagstagramers","drake","2011","skate","classy","pop","macro","hungergames","hk",
            "harrypotter","bar","jesus","fotorus","instagramtagsdotcom","waiting","diy","outdoors","directioners",
            "mcdonalds","djmalik","missyou","hehe","child","movies","what","awesome_shots","love","instagood","me",
            "cute","tbt","photooftheday","instamood","tweegram","iphonesia","picoftheday","igers","summer","girl",
            "instadaily","beautiful","instagramhub","iphoneonly","igdaily","bestoftheday","follow","webstagram",
            "picstitch","jj","happy","sky","nofilter","fashion","followme","fun","sun","smile","instagramers",
            "food","pretty","friends","nature","onedirection","hair","beach","lol","like","swag","dog","funny",
            "blue","life","bored","cool","sunset","versagram","instagoodme","cute","tbt","photooftheday","instamood",
            "tweegram","iphonesia","picoftheday","igers","summer","girl","instadaily","beautiful","instagramhub",
            "iphoneonly","igdaily","bestoftheday","follow","webstagram","picstitch","jj","happy","sky","nofilter",
            "fashion","followme","fun","sun","smile","instagramers","food","pretty","friends","nature","onedirection",
            "hair","beach","lol","like","swag","dog","funny","blue","life","bored","cool","sunset","versagram","coffee",
            "to","quote","forever","nike","drawing","pet","drunk","gf_daily","travel","bff","follow4follow","brother",
            "f4f","clubsocial","so","view","kiss","a","instagrammer","goodtimes","starbucks","landscape","today",
            "vacation","street","cutie","football","brown","gay","tagsforlikes","swedish","sisters","icecream","cats",
            "pic","holiday","sunny","live","tan","pool","shopping","italy","with","architecture","myself","sad","it",
            "japan","lake","best","louistomlinson","liampayne","instacollage","blonde","bestfriends","1d","puppy",
            "flowers","work","instacool","makeup","shoes","insta","adorable","birthday","friend","10likes","likeforlike",
            "gang_family","boyfriend","good","nyc","morning","you","instapic","the","sea","new","blackandwhite","haha","instaphoto",
            "jusgramm","day","tree","dinner","crazy","20likes","like4like","shoutout","trees","sister","throwback",
            "tattoo","and","tired","home","gorgeous","true","canada","happybirthday","relaxing","nephew","ink","pitbull","instacanvas",
            "homecoming","catstagram","paint","igersturkey","selfportrait","fireworks","all","batman","ipod","top","guitar",
            "instaweatherpro","scary","taylorswift","snapseed","colour","back","bike","paradise","cheese","febphotoaday","boring",
            "justme","lmfao","hongkong","nail","followher","stupid","believe","texas","cupcake","yes","baseball","3","brasil","ever",
            "besties","workflow","realtalk","pictures","alcohol","bomb","420","moon","boss","hate","instatags","mac","trip","class",
            "country","curly","highschool","uk","train","mountains","instaweather","jewelry","heaven","america","horse","song","real",
            "dad","hi","fit","painting","swagg","october","selenagomez","jewlery","swimming","basketball","hand","jealous","facebook",
            "jdm","igersitalia","swedishgirl","mountain","window","yeah","bright","justdoit","australia","photowall","singapore","ny",
            "ice","self","england","christmas","true","delicious","chocolate","sweden","picture","gmy","car","old","iphonography",
            "followforfollow","instagrammers","yellow","loveher","lovely","random","truth","perfect","colors","heart","model","light",
            "london","kik","ootd","vintage","iphonegraphy","breakfast","fall","lips","color","pictureoftheday","loveit","memories",
            "teamfollowback","in","dress","city","peace","justinbieber","purple","ocean","instafamous","kitty","beer","lunch","rain",
            "instafood","cake","brunette","face","orange","doubletap","miss","thailand","florida","lovethem","for","lights","primeshots",
            "autumn","inspiration","outside","weird","saturday","gym","young","on","of","movie","building","fml","house","natural",
            "bikini","iger","sick","wtf","directioner","instamessage","mom","girly","halloween","laugh","college","norway","fire",
            "indonesia","excited","brazil","grass","100likes","likeback","photoaday","tattoos","tumblr","her","50likes","s4s","candy",
            "clothes","vans", "best","louistomlinson","liampayne","instacollage","blonde","bestfriends","1d","puppy","flowers","work","instacool","makeup","shoes","insta",
            "adorable","birthday","friend","10likes","likeforlike","gang_family","boyfriend",
            "good","nyc","morning","you","instapic","the","sea","new","blackandwhite","haha","instaphoto","jusgramm","day","tree",
            "dinner","crazy","20likes","like4like","shoutout","trees","sister","throwback","tattoo","and","tired","home","gorgeous","true"
        ) );
}

function getAdTags(){
    
        return join(',', array(
			"coffee","to","quote","forever","nike","drawing","pet","drunk","gf_daily","travel","bff","follow4follow","brother",
			"f4f","clubsocial","so","view","kiss","a","instagrammer","goodtimes","starbucks","landscape","today","vacation",
			"street","cutie","football","brown","gay","tagsforlikes","swedish","sisters","icecream","cats","pic","holiday",
			"sunny","live","tan","pool","shopping","italy","with","architecture","myself","sad","it","japan","lake","chocolate",
			"sweden","picture","gmy","car","old","iphonography","followforfollow","instagrammers","yellow","loveher","lovely",
			"random","truth","perfect","colors","heart","model","light","london","kik","ootd","vintage","iphonegraphy",
			"breakfast","fall","lips","color","pictureoftheday","loveit","memories","teamfollowback","in","dress","city",
			"peace","justinbieber","purple","ocean","instafamous","kitty","beer","lunch","rain","instafood","cake","brunette",
			"face","orange","true","delicious","chocolate","sweden","picture","gmy","car","old","iphonography","followforfollow",
			"instagrammers","yellow","loveher","lovely","random","truth","perfect","colors","heart","model","light","london",
			"kik","ootd","vintage","iphonegraphy","breakfast","fall","lips","color","pictureoftheday","loveit","memories",
			"teamfollowback","in","dress","city","peace","justinbieber","purple","ocean","instafamous","kitty","beer","lunch",
			"rain","instafood","cake","brunette","face","orange","420","moon","boss","hate","instatags","mac","trip","class",
			"country","curly","highschool","uk","train","mountains","instaweather","jewelry","heaven","america","horse","song",
			"real","dad","hi","fit","painting","swagg","october","selenagomez","jewlery","swimming","basketball","hand",
			"jealous","facebook","jdm","igersitalia","swedishgirl","mountain","window","yeah","bright","justdoit","australia",
			"photowall","singapore","ny","ice","self","england","christmas","iphotography","followbackteam","berlin","highlife",
			"strong","shop","last","indian","fluffy","stylish","60likes","iphonephoto","ginger","do","banana","drinking",
			"shots","much","milk","need","toy","hollywood","lasvegas","5","fact","likeit","puppies","hey","win","instaddict",
			"after","cantwait","eating","closeup","jb","giants","happythanksgiving","dreams","dank","daily","damn","instahappy",
			"flag","igerspinoy","xoxo","kicks","amsterdam","early","addicted","favorite","hipstamatic","cold","disney","fitness",
			"2","sunrise","time","instafashion","skyporn","nomakeup","design","sand","dope","cloudporn","streetphotography",
			"graffiti","sleepy","apple","ifollowback","louis","is","gold","igersoftheday","igersmanila","zayn","winter",
			"little","bed","cousin","shirt","petstagram","garden","likes","silly","nailpolish","instagroove","shorts",
			"workout","keepcalm","park","eye","lmao","liam","dessert","kuwait","no","kitten","instafun","lipstick","kpop",
			"faded","dead","edit","neon","eat","bestagram","jordan","oldschool","waves","bow","boots","implus_daily","bieber",
			"cookies","yumm","wall","artist","istanbul","tgif","chihuahua","ily","instaflair","cali","driving","hope","justin",
			"curlyhair","alone","hashtag","silver","photos","hotel","ighub","we","niece","be","salad","proud","graduation",
			"accessories","bad","disneyland","instaaddict","forest","duckface","ready","finally","instagood","me","cute",
			"tbt","photooftheday","instamood","tweegram","iphonesia","picoftheday","igers","summer","girl","instadaily",
			"beautiful","instagramhub","iphoneonly","igdaily","bestoftheday","follow","webstagram","picstitch","jj","happy",
			"sky","nofilter","fashion","followme","fun","sun","smile","instagramers","food","pretty","friends","nature",
			"onedirection","hair","beach","lol","like","swag","dog","funny","blue","life","bored","cool","sunset","versagram"
        )
    );
}
